### ISSUE TITLE
Devices with spaces in their names aren't linked to properly

### ISSUE THREAD

**Issue by spottyict** [microlith57/boop#17]
Steps to reproduce:

1. Create Device name with space
2. Find device in list and click on link to device details.
3. `404`.
4. Re-add a hyphen in place where space would be in URL and link to details page works.

**Comment by microlith57** [comment]
This is because the device schema looks like this:
```ruby
string "name"
string "description"
datetime "created_at", null: false
datetime "updated_at", null: false
```
whereas the borrower schema looks like this:
```ruby
string "name"
string "email"
integer "allowance"
datetime "created_at", null: false
datetime "updated_at", null: false
string "code"
index ["code"], name: "index_borrowers_on_code", unique: true
```

Will need to add a `code` column to devices as a unique index (and remove the unique index on the name); this is easy enough but will require a migration to create new codes for existing devices

**Comment by microlith57** [comment]
Fixed in develop
